default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: api-addicts_development

test:
  <<: *default
  database: api-addicts_test

production:
  <<: *default
  database: api-addicts_production
  username: api-addicts
  password: <%= ENV['API-ADDICTS_DATABASE_PASSWORD'] %>
